[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true

# https://github.com/johnthagen/min-sized-rust
[profile.web]
inherits = "release"
opt-level = "z"
strip = true
