[package]
name = "rosebush-web"
version = "0.0.0"
publish = false
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1"
rosebush = { path = "../core" }
rosebush-frontend = { path = "../frontend" }
wasm-bindgen = "=0.2.84"
