[package]
name = "rose-interp"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
rose = { path = "../core" }
serde = { version = "1", features = ["derive", "rc"], optional = true }
thiserror = "1"

[dev-dependencies]
ts-rs = "6"

[features]
serde = ["dep:serde"]
