[package]
name = "rose"
version = "0.0.0"
edition = "2021"
description = "Extensible interactive autodiff."
license = "MIT"
include = ["src/lib.rs"]

[dependencies]
ts-rs = "6.1"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2.84"

[features]
serde-enable = []
