name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: site

  pages:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v1
